### ISSUE TITLE
About the sample quality

### ISSUE THREAD

**Issue by jianshu-qin** [NUAAerJC/classifier-free-diffusion-guidance#3]
I try an implementation of the classifier-free diffusion  which is mainly adapted from the classifier-guided diffusion and using your training hyperparameters on CiFar10. But I got a FID score between 4.1 and 4.2 when the w was set to 0.1 and 0.2. It's worse than the original DDPM. Could you please tell me your sample quality? Thank you very much!

**Comment by jcwang-gh** [comment]
Excellent questions! I'm glad you ask it. In my opinion, there are several reasons for this issue:
1.  official classifier-free diffusion guidance model is trained for millions of steps according to the paper.

> The 64 × 64 models used sampler noise interpolation
coefficient v = 0.3 and were trained for 400 thousand steps; the 128 × 128 models used v = 0.2 and
were trained for 2.7 million steps.

The original DDPM is also trained for millions of steps:

> We used TPU v3-8 (similar to 8 V100 GPUs) for all experiments. Our CIFAR model trains at 21
steps per second at batch size 128 (10.6 hours to train to completion at 800k steps), and sampling
a batch of 256 images takes 17 seconds. Our CelebA-HQ/LSUN (2562) models train at 2.2 steps
per second at batch size 64, and sampling a batch of 128 images takes 300 seconds. We trained on
CelebA-HQ for 0.5M steps, LSUN Bedroom for 2.4M steps, LSUN Cat for 1.8M steps, and LSUN
Church for 1.2M steps. The larger LSUN Bedroom model was trained for 1.15M steps.

> We set the batch size to 128 for CIFAR10 and 64 for larger images. We did not sweep over
these values.

whereas my model is just trained for tens of thousand steps. The amount of cifar-10 training set is 50 000, the batch size I used is 1024, and I set the parameter drop_last = True. Therefore, during each epoch the model takes 50 000 / 1024 = 48 steps or so. My model is trained for 1000 epochs by default. So the total number of steps is 48 000,  which is one tenth or maybe one percent of their training steps. If you want to get better performance, maybe you should change the batch size and train your model for more epochs. 

2. For simplicity, I do not use the attention block provided by openAI implementation and change the network architecture in order to make the model smaller, which may cause performance degradation.
3. Several data augmentation techniques are used when training the original DDPM according to the paper:

> We used random horizontal flips during training for CIFAR10; we tried training both with
and without flips, and found flips to improve sample quality slightly. We also used random
horizontal flips for all other datasets except LSUN Bedroom.
4. EMA is used when training the original DDPM and I guess it is widely used in most of variants of DDPM.
However, I do not use this technique in my code for simplicity.
> We used EMA on model parameters with a decay factor of 0.9999. We did not sweep over
this value.

I will make some improvements of my code in one or two weeks. Hope my explanations help you!

**Comment by Triocrossing** [comment]
> EMA is used when training the original DDPM and I guess it is widely used in most of variants of DDPM.
However, I do not use this technique in my code for simplicity.

Emm, I do think the EMA is critical for diffusion models to reach a stable training in terms of the performance.
