### ISSUE TITLE
Questions about the your Cosine noisy scheduler

### ISSUE THREAD

**Issue by George0726** [NUAAerJC/classifier-free-diffusion-guidance#7]
Thanks for your impressive work!  I am still wondering if you have tested the cosine noise scheduler. I have tried the cosine noise scheduler but the result is kind of wired.

![image](https://github.com/coderpiaobozhe/classifier-free-diffusion-guidance-Pytorch/assets/38740075/3ec6fbd5-849d-4d10-b315-7a25a1c7fc9b)

**Comment by jcwang-gh** [comment]
The file *utils.py* comes from [openai/guided-diffusion](https://github.com/openai/guided-diffusion) and I have not tested cosine noise scheduler yet. Sorry for the inconvenience. I think the reason is that some values of alphas_bar are too small for diffusion model to incorrect the error during the first few sampling steps.

**Comment by George0726** [comment]
Sure no problem! Thanks for your reply,

**Comment by xiaoerjason** [comment]
我发现这个预先优化器是不正确的，正在解决它
![屏幕截图 2024-08-12 140228](https://github.com/user-attachments/assets/fc249ed2-b604-485c-90e2-2cc749ca935f)
